#ifndef _HAKO_CONFIG_HPP_
#define _HAKO_CONFIG_HPP_

#define HAKO_FIXED_STRLEN_MAX       256
#define HAKO_DATA_MAX_ASSET_NUM     128

#define HAKO_SHARED_MEMORY_BASE_ID   0x00FF
#define HAKO_SHARED_MEMORY_ID_0     (0x0 + HAKO_SHARED_MEMORY_BASE_ID)


#endif /* _HAKO_CONFIG_HPP_ */