
name: Hakoniwa.dll
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get DateTime
      id: date
      run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    - name: Build
      run: |
        bash ./impl/asset/server/csharp/HakoniwaCore/build_by_docker.bash Rebuild Debug
      shell: bash
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Hakoniwa.dll.${{ steps.date.outputs.date }}
        draft: true
        prerelease: false
        files: |
          dst/Hakoniwa.deps.json
          dst/Hakoniwa.dll
          dst/Hakoniwa.pdb
          dst/Hakoniwa_NoGRPC.deps.json
          dst/Hakoniwa_NoGRPC.dll
          dst/Hakoniwa_NoGRPC.pdb
